name: CICD2
run-name: Unit Test (python2)
on:
  push:
  workflow_run:
    workflows:
      - CICD
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 6.0
      - uses: actions/checkout@v3
      - name: Set up Python all python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: pip install -e ".[dev,test]"
      - name: PythonPath
        run: echo "PYTHONPATH=src/" >> $GITHUB_ENV
      - name: Run Test
        run: python -m unittest discover -s tests
